# Generated by Django 5.2.4 on 2025-07-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='level',
            field=models.CharField(choices=[('primary', 'İlkokul'), ('middle', 'Ortaokul'), ('high', 'Lise'), ('university', 'Üniversite'), ('general', 'Genel')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='baslık yok', max_length=200),
            preserve_default=False,
        ),
    ]
