# Generated by Django 5.2.4 on 2025-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='listing_images/'),
        ),
    ]
