# Generated by Django 5.2.4 on 2025-07-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0012_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
    ]
