# Generated by Django 5.2.4 on 2025-07-11 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('primary', 'İlkokul'), ('middle', 'Ortaokul'), ('high', 'Lise'), ('university', 'Üniversite'), ('general', 'Genel')], default='general', max_length=20)),
                ('listing_type', models.CharField(choices=[('book', 'Kitap'), ('note', 'Ders Notu')], max_length=10)),
                ('donation_type', models.CharField(choices=[('free', 'Bağış'), ('paid', 'Ücretli')], max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('page_count', models.PositiveIntegerField()),
                ('related_course', models.CharField(max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('valid_year', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_level', models.CharField(blank=True, choices=[('low', 'Az Çözülmüş'), ('medium', 'Orta Çözülmüş'), ('high', 'Çok Çözülmüş'), ('full', 'Hepsi Çözülmüş')], max_length=10, null=True)),
                ('publish_year', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='listing_images/default.png', null=True, upload_to='listing_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
